// This file was auto-generated by Fern from our API Definition.

package team

import (
	fern "github.com/mixed-file-directory/fern"
)

type UpdateWageSettingRequest struct {
	// The new `WageSetting` object that completely replaces the existing one.
	WageSetting *fern.WageSetting `json:"wage_setting,omitempty" url:"-"`
}
