// This file was auto-generated by Fern from our API Definition.

package object

import (
	context "context"
	fern "github.com/mixed-file-directory/fern"
	catalog "github.com/mixed-file-directory/fern/catalog"
	core "github.com/mixed-file-directory/fern/core"
	option "github.com/mixed-file-directory/fern/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Creates or updates the target [CatalogObject](entity:CatalogObject).
func (c *Client) Upsert(
	ctx context.Context,
	request *catalog.UpsertCatalogObjectRequest,
	opts ...option.RequestOption,
) (*fern.UpsertCatalogObjectResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/catalog/object"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.UpsertCatalogObjectResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Returns a single [CatalogItem](entity:CatalogItem) as a
// [CatalogObject](entity:CatalogObject) based on the provided ID. The returned
// object includes all of the relevant [CatalogItem](entity:CatalogItem)
// information including: [CatalogItemVariation](entity:CatalogItemVariation)
// children, references to its
// [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of
// any [CatalogTax](entity:CatalogTax) objects that apply to it.
func (c *Client) Get(
	ctx context.Context,
	// The object ID of any type of catalog objects to be retrieved.
	objectId string,
	request *catalog.ObjectGetRequest,
	opts ...option.RequestOption,
) (*fern.GetCatalogObjectResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/catalog/object/%v", objectId)

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetCatalogObjectResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Deletes a single [CatalogObject](entity:CatalogObject) based on the
// provided ID and returns the set of successfully deleted IDs in the response.
// Deletion is a cascading event such that all children of the targeted object
// are also deleted. For example, deleting a [CatalogItem](entity:CatalogItem)
// will also delete all of its
// [CatalogItemVariation](entity:CatalogItemVariation) children.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the catalog object to be deleted. When an object is deleted, other
	// objects in the graph that depend on that object will be deleted as well (for example, deleting a
	// catalog item will delete its catalog item variations).
	objectId string,
	opts ...option.RequestOption,
) (*fern.DeleteCatalogObjectResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/catalog/object/%v", objectId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.DeleteCatalogObjectResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodDelete,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
