// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/mixed-file-directory/fern/core"
)

type MerchantsListRequest struct {
	// The cursor generated by the previous response.
	Cursor *int `json:"-" url:"cursor,omitempty"`
}

// The response object returned by the [RetrieveMerchant](api-endpoint:Merchants-RetrieveMerchant) endpoint.
type GetMerchantResponse struct {
	// Information on errors encountered during the request.
	Errors []*Error `json:"errors,omitempty" url:"errors,omitempty"`
	// The requested `Merchant` object.
	Merchant *Merchant `json:"merchant,omitempty" url:"merchant,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetMerchantResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMerchantResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMerchantResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMerchantResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMerchantResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// The response object returned by the [ListMerchant](api-endpoint:Merchants-ListMerchants) endpoint.
type ListMerchantsResponse struct {
	// Information on errors encountered during the request.
	Errors []*Error `json:"errors,omitempty" url:"errors,omitempty"`
	// The requested `Merchant` entities.
	Merchant []*Merchant `json:"merchant,omitempty" url:"merchant,omitempty"`
	// If the response is truncated, the cursor to use in next request to fetch next set of objects.
	Cursor *int `json:"cursor,omitempty" url:"cursor,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (l *ListMerchantsResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListMerchantsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListMerchantsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListMerchantsResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties

	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMerchantsResponse) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
