// This file was auto-generated by Fern from our API Definition.

package teammemberprofiles

import (
	context "context"
	fmt "fmt"
	fern "github.com/mixed-file-directory/fern"
	bookings "github.com/mixed-file-directory/fern/bookings"
	core "github.com/mixed-file-directory/fern/core"
	option "github.com/mixed-file-directory/fern/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Lists booking profiles for team members.
func (c *Client) List(
	ctx context.Context,
	request *bookings.TeamMemberProfilesListRequest,
	opts ...option.RequestOption,
) (*core.Page[*fern.TeamMemberBookingProfile], error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/bookings/team-member-booking-profiles"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	prepareCall := func(pageRequest *core.PageRequest[*string]) *core.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("cursor", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &core.CallParams{
			URL:         nextURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    pageRequest.Response,
		}
	}
	readPageResponse := func(response *fern.ListTeamMemberBookingProfilesResponse) *core.PageResponse[*string, *fern.TeamMemberBookingProfile] {
		next := response.Cursor
		results := response.TeamMemberBookingProfiles
		return &core.PageResponse[*string, *fern.TeamMemberBookingProfile]{
			Next:    next,
			Results: results,
		}
	}
	pager := core.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Retrieves a team member's booking profile.
func (c *Client) Get(
	ctx context.Context,
	// The ID of the team member to retrieve.
	teamMemberId string,
	opts ...option.RequestOption,
) (*fern.GetTeamMemberBookingProfileResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/bookings/team-member-booking-profiles/%v", teamMemberId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetTeamMemberBookingProfileResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
