// This file was auto-generated by Fern from our API Definition.

package labor

import (
	fern "github.com/mixed-file-directory/fern"
)

type CreateShiftRequest struct {
	// A unique string value to ensure the idempotency of the operation.
	IdempotencyKey *string `json:"idempotency_key,omitempty" url:"-"`
	// The `Shift` to be created.
	Shift *fern.Shift `json:"shift,omitempty" url:"-"`
}

type SearchShiftsRequest struct {
	// Query filters.
	Query *fern.ShiftQuery `json:"query,omitempty" url:"-"`
	// The number of resources in a page (200 by default).
	Limit *int `json:"limit,omitempty" url:"-"`
	// An opaque cursor for fetching the next page.
	Cursor *string `json:"cursor,omitempty" url:"-"`
}

type UpdateShiftRequest struct {
	// The updated `Shift` object.
	Shift *fern.Shift `json:"shift,omitempty" url:"-"`
}
