// This file was auto-generated by Fern from our API Definition.

package labor

import (
	fern "github.com/mixed-file-directory/fern"
)

type UpdateWorkweekConfigRequest struct {
	// The updated `WorkweekConfig` object.
	WorkweekConfig *fern.WorkweekConfig `json:"workweek_config,omitempty" url:"-"`
}

type WorkweekConfigsListRequest struct {
	// The maximum number of `WorkweekConfigs` results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// A pointer to the next page of `WorkweekConfig` results to fetch.
	Cursor *string `json:"-" url:"cursor,omitempty"`
}
