// This file was auto-generated by Fern from our API Definition.

package client

import (
	context "context"
	fmt "fmt"
	fern "github.com/mixed-file-directory/fern"
	core "github.com/mixed-file-directory/fern/core"
	activities "github.com/mixed-file-directory/fern/giftcards/activities"
	option "github.com/mixed-file-directory/fern/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Activities *activities.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:     options.ToHeader(),
		Activities: activities.NewClient(opts...),
	}
}

// Lists all gift cards. You can specify optional filters to retrieve
// a subset of the gift cards. Results are sorted by `created_at` in ascending order.
func (c *Client) List(
	ctx context.Context,
	request *fern.GiftCardsListRequest,
	opts ...option.RequestOption,
) (*core.Page[*fern.GiftCard], error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/gift-cards"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	prepareCall := func(pageRequest *core.PageRequest[*string]) *core.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("cursor", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &core.CallParams{
			URL:         nextURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    pageRequest.Response,
		}
	}
	readPageResponse := func(response *fern.ListGiftCardsResponse) *core.PageResponse[*string, *fern.GiftCard] {
		next := response.Cursor
		results := response.GiftCards
		return &core.PageResponse[*string, *fern.GiftCard]{
			Next:    next,
			Results: results,
		}
	}
	pager := core.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Creates a digital gift card or registers a physical (plastic) gift card. After the gift card
// is created, you must call [CreateGiftCardActivity](api-endpoint:GiftCardActivities-CreateGiftCardActivity)
// to activate the card with an initial balance before it can be used for payment.
func (c *Client) Create(
	ctx context.Context,
	request *fern.CreateGiftCardRequest,
	opts ...option.RequestOption,
) (*fern.CreateGiftCardResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/gift-cards"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.CreateGiftCardResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Retrieves a gift card using the gift card account number (GAN).
func (c *Client) GetFromGan(
	ctx context.Context,
	request *fern.GetGiftCardFromGanRequest,
	opts ...option.RequestOption,
) (*fern.GetGiftCardFromGanResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/gift-cards/from-gan"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetGiftCardFromGanResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Retrieves a gift card using a secure payment token that represents the gift card.
func (c *Client) GetFromNonce(
	ctx context.Context,
	request *fern.GetGiftCardFromNonceRequest,
	opts ...option.RequestOption,
) (*fern.GetGiftCardFromNonceResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/v2/gift-cards/from-nonce"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetGiftCardFromNonceResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Links a customer to a gift card, which is also referred to as adding a card on file.
func (c *Client) LinkCustomer(
	ctx context.Context,
	// The ID of the gift card to be linked.
	giftCardId string,
	request *fern.LinkCustomerToGiftCardRequest,
	opts ...option.RequestOption,
) (*fern.LinkCustomerToGiftCardResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/gift-cards/%v/link-customer", giftCardId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.LinkCustomerToGiftCardResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Unlinks a customer from a gift card, which is also referred to as removing a card on file.
func (c *Client) UnlinkCustomer(
	ctx context.Context,
	// The ID of the gift card to be unlinked.
	giftCardId string,
	request *fern.UnlinkCustomerFromGiftCardRequest,
	opts ...option.RequestOption,
) (*fern.UnlinkCustomerFromGiftCardResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/gift-cards/%v/unlink-customer", giftCardId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.UnlinkCustomerFromGiftCardResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Retrieves a gift card using the gift card ID.
func (c *Client) Get(
	ctx context.Context,
	// The ID of the gift card to retrieve.
	id string,
	opts ...option.RequestOption,
) (*fern.GetGiftCardResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/gift-cards/%v", id)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetGiftCardResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
