// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/mixed-file-directory/fern/core"
	option "github.com/mixed-file-directory/fern/option"
	actions "github.com/mixed-file-directory/fern/terminal/actions"
	checkouts "github.com/mixed-file-directory/fern/terminal/checkouts"
	refunds "github.com/mixed-file-directory/fern/terminal/refunds"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Actions   *actions.Client
	Checkouts *checkouts.Client
	Refunds   *refunds.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Actions:   actions.NewClient(opts...),
		Checkouts: checkouts.NewClient(opts...),
		Refunds:   refunds.NewClient(opts...),
	}
}
