// This file was auto-generated by Fern from our API Definition.

package webhooks

type EventTypesListRequest struct {
	// The API version for which to list event types. Setting this field overrides the default version used by the application.
	ApiVersion *string `json:"-" url:"api_version,omitempty"`
}
