// This file was auto-generated by Fern from our API Definition.

package wagesetting

import (
	context "context"
	fern "github.com/mixed-file-directory/fern"
	core "github.com/mixed-file-directory/fern/core"
	option "github.com/mixed-file-directory/fern/option"
	team "github.com/mixed-file-directory/fern/team"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Retrieves a `WageSetting` object for a team member specified
// by `TeamMember.id`.
// Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#retrievewagesetting).
func (c *Client) Get(
	ctx context.Context,
	// The ID of the team member for which to retrieve the wage setting.
	teamMemberId string,
	opts ...option.RequestOption,
) (*fern.GetWageSettingResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/team-members/%v/wage-setting", teamMemberId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.GetWageSettingResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Creates or updates a `WageSetting` object. The object is created if a
// `WageSetting` with the specified `team_member_id` does not exist. Otherwise,
// it fully replaces the `WageSetting` object for the team member.
// The `WageSetting` is returned on a successful update.
// Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#create-or-update-a-wage-setting).
func (c *Client) Update(
	ctx context.Context,
	// The ID of the team member for which to update the `WageSetting` object.
	teamMemberId string,
	request *team.UpdateWageSettingRequest,
	opts ...option.RequestOption,
) (*fern.UpdateWageSettingResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://connect.squareupsandbox.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := core.EncodeURL(baseURL+"/v2/team-members/%v/wage-setting", teamMemberId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *fern.UpdateWageSettingResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPut,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
