/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as FernDocsConfig from "../../../../api";
import * as core from "../../../../core";

export const ApiScrollingConfiguration: core.serialization.Schema<
    serializers.ApiScrollingConfiguration.Raw,
    FernDocsConfig.ApiScrollingConfiguration
> = core.serialization.enum_(["infinite", "paginated"]);

export declare namespace ApiScrollingConfiguration {
    type Raw = "infinite" | "paginated";
}
