// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/mixed-file-directory/fern/core"
	option "github.com/mixed-file-directory/fern/option"
	batch "github.com/mixed-file-directory/fern/v1/batch"
	transactionsclient "github.com/mixed-file-directory/fern/v1/transactions/client"
	webhooks "github.com/mixed-file-directory/fern/v1/webhooks"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Batch        *batch.Client
	Transactions *transactionsclient.Client
	Webhooks     *webhooks.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:       options.ToHeader(),
		Batch:        batch.NewClient(opts...),
		Transactions: transactionsclient.NewClient(opts...),
		Webhooks:     webhooks.NewClient(opts...),
	}
}
