// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/mixed-file-directory/fern/core"
	codes "github.com/mixed-file-directory/fern/devices/codes"
	option "github.com/mixed-file-directory/fern/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Codes *codes.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
		Codes:  codes.NewClient(opts...),
	}
}
