// This file was auto-generated by Fern from our API Definition.

package catalog

type ImagesCreateRequest struct {
	Request interface{} `json:"request,omitempty" url:"-"`
}

type ImagesUpdateRequest struct {
	Request interface{} `json:"request,omitempty" url:"-"`
}
