/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernOpenapiIr from "../../..";

export interface WebhookExample extends FernOpenapiIr.WithDescription {
    name: string | undefined;
    payload: FernOpenapiIr.FernExample | undefined;
}
