/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FernOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { WithDescription } from "../../commons/types/WithDescription";
import { WithSource } from "../../commons/types/WithSource";
import { WithContentType } from "../../commons/types/WithContentType";

export const JsonRequest: core.serialization.ObjectSchema<serializers.JsonRequest.Raw, FernOpenapiIr.JsonRequest> =
    core.serialization
        .objectWithoutOptionalProperties({
            schema: core.serialization.lazy(() => serializers.Schema),
            additionalProperties: core.serialization.boolean(),
        })
        .extend(WithDescription)
        .extend(WithSource)
        .extend(WithContentType);

export declare namespace JsonRequest {
    interface Raw extends WithDescription.Raw, WithSource.Raw, WithContentType.Raw {
        schema: serializers.Schema.Raw;
        additionalProperties: boolean;
    }
}
