/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as FernOpenapiIr from "../../../../api";
import * as core from "../../../../core";

export const WebhookExample: core.serialization.ObjectSchema<
    serializers.WebhookExample.Raw,
    FernOpenapiIr.WebhookExample
> = core.serialization
    .objectWithoutOptionalProperties({
        name: core.serialization.string().optional(),
        payload: core.serialization.lazy(async () => (await import("../../..")).SchemaWithExample),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).WithDescription));

export declare namespace WebhookExample {
    interface Raw extends serializers.WithDescription.Raw {
        name?: string | null;
        payload: serializers.SchemaWithExample.Raw;
    }
}
