// This file was auto-generated by Fern from our API Definition.

package terminal

import (
	fern "github.com/mixed-file-directory/fern"
)

type CancelTerminalActionRequest struct {
}

type CreateTerminalActionRequest struct {
	// A unique string that identifies this `CreateAction` request. Keys can be any valid string
	// but must be unique for every `CreateAction` request.
	//
	// See [Idempotency keys](https://developer.squareup.com/docs/basics/api101/idempotency) for more
	// information.
	IdempotencyKey string `json:"idempotency_key" url:"-"`
	// The Action to create.
	Action *fern.TerminalAction `json:"action,omitempty" url:"-"`
}

type SearchTerminalActionsRequest struct {
	// Queries terminal actions based on given conditions and sort order.
	// Leaving this unset will return all actions with the default sort order.
	Query *fern.TerminalActionQuery `json:"query,omitempty" url:"-"`
	// A pagination cursor returned by a previous call to this endpoint.
	// Provide this to retrieve the next set of results for the original query.
	// See [Pagination](https://developer.squareup.com/docs/basics/api101/pagination) for more
	// information.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Limit the number of results returned for a single request.
	Limit *int `json:"limit,omitempty" url:"-"`
}
